# -*- coding: utf-8 -*-
"""get_papers_list.py python Copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4Rd76A73LZHiOBqX5CDvKCpdufPaGkN
"""

import argparse
from get_papers import fetch_and_process_papers

def main():
    parser = argparse.ArgumentParser(description="Fetch research papers from PubMed based on a query.")
    parser.add_argument('query', type=str, help="The query to search PubMed.")
    parser.add_argument('-d', '--debug', action='store_true', help="Print debug information.")
    parser.add_argument('-f', '--file', type=str, help="The filename to save results.")
    args = parser.parse_args()

    companies = ['Pfizer', 'Johnson & Johnson', 'AstraZeneca', 'Merck', 'Novartis', 'Roche']

    if args.debug:
        print(f"Query: {args.query}")
        print(f"Output file: {args.file}")

    fetch_and_process_papers(args.query, companies, output_file=args.file)


if __name__ == "__main__":
    main()